# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Corvo < Formula
  desc "Language-agnostic distributed job processing system"
  homepage "https://corvohq.com"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/corvohq/corvo/releases/download/v0.3.0/corvo_0.3.0_darwin_amd64.tar.gz"
      sha256 "b52d0942e129ae5cb8da439a1e4655dd53112af7bb23cf2ee5db1593636a30cf"

      def install
        bin.install "corvo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/corvohq/corvo/releases/download/v0.3.0/corvo_0.3.0_darwin_arm64.tar.gz"
      sha256 "c6aab75656f15d883fdf67a7341367d3056166822c8f7e0dbc834da1a42b2105"

      def install
        bin.install "corvo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/corvohq/corvo/releases/download/v0.3.0/corvo_0.3.0_linux_amd64.tar.gz"
      sha256 "e1423521056fe1f7cf0f834dea24fab41797784ece4c07fa711b4923978f4e74"
      def install
        bin.install "corvo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/corvohq/corvo/releases/download/v0.3.0/corvo_0.3.0_linux_arm64.tar.gz"
      sha256 "bf98d7e892f084fdb2b1b22f903de414ce859e9d9f53d7934eb8dd59db49034a"
      def install
        bin.install "corvo"
      end
    end
  end

  test do
    system "#{bin}/corvo", "--version"
  end
end
