# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Corvo < Formula
  desc "Language-agnostic distributed job processing system"
  homepage "https://corvohq.com"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/corvohq/corvo/releases/download/v0.0.1/corvo_0.0.1_darwin_amd64.tar.gz"
      sha256 "26f1c430f982a4a78a5953e9ad245344e10e3c9aee0f7bc4b8d4a3b11560ad70"

      def install
        bin.install "corvo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/corvohq/corvo/releases/download/v0.0.1/corvo_0.0.1_darwin_arm64.tar.gz"
      sha256 "3da4f8c8cf3ae5214b9ddfcd9991cddec8fd7122d5ee13c7fe156801ed4ec480"

      def install
        bin.install "corvo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/corvohq/corvo/releases/download/v0.0.1/corvo_0.0.1_linux_amd64.tar.gz"
      sha256 "f0a4f50506e389de43f6d552d5e303ad14d958c079554b94a5cd8aa87a73085a"
      def install
        bin.install "corvo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/corvohq/corvo/releases/download/v0.0.1/corvo_0.0.1_linux_arm64.tar.gz"
      sha256 "0d2083898307941dd4dda6db955547b73fd3dec77cc1397fb8f9acaea680a082"
      def install
        bin.install "corvo"
      end
    end
  end

  test do
    system "#{bin}/corvo", "--version"
  end
end
